# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.extension:
        class: App\AppBundle\Twig\Extension\AppExtension
        tags:
            -  { name: twig.extension }
    user.registration_complete:
        class: App\AppBundle\EventListener\RegistrationConfirmListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }