moderation:
    path:     /
    defaults: { _controller: AppAppBundle:Moderation:index }

moderation_new:
    path:     /new
    defaults: { _controller: AppAppBundle:Moderation:new }

moderation_declined:
    path:     /declined
    defaults: { _controller: AppAppBundle:Moderation:declined }

moderation_approve:
    path:     /approve/{id}
    defaults: { _controller: AppAppBundle:Moderation:approve }

moderation_decline:
    path:     /decline/{id}
    defaults: { _controller: AppAppBundle:Moderation:decline }