nodes:
    path:     /
    defaults: { _controller: AppAppBundle:Nodes:index }

nodes_search:
    path:     /search
    defaults: { _controller: AppAppBundle:Nodes:getSearch }
    methods: [GET]

nodes_search_action:
    path:     /search
    defaults: { _controller: AppAppBundle:Nodes:postSearch }
    methods: [POST]

nodes_add:
    path:     /secure/add
    defaults: { _controller: AppAppBundle:Nodes:getAdd }
    methods: [GET]

nodes_add_action:
    path:     /secure/add
    defaults: { _controller: AppAppBundle:Nodes:postAdd }
    methods: [POST]

nodes_add_synonym:
    path:     /secure/add-synonym
    defaults: { _controller: AppAppBundle:Nodes:postAddSynonym }
    methods: [POST]

nodes_graph:
    path:     /graph/{id}
    defaults: { _controller: AppAppBundle:Nodes:getGraph }